Translations
sellmark/dota-discord-bot pull request #9
Opened 2024-02-29 22:15 UTC by PogSmok

Wyczekiwane tłumaczenia z JSON-ów.

2024-03-01 10:52 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "PL.json"), encoding='utf-8') as polish_file:
Hej, tu nie przesadziłeś z odgadywaniem tej ścieżki? :D

2024-03-01 10:52 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "PL.json"), encoding='utf-8') as polish_file:
W sensie - nie idzie krócej tego zrobić?

2024-03-01 11:00 UTC, sellmark requested changes
Proszę zapoznaj się z komentarzami

2024-03-01 11:00 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +#ideally this should be in a separate file/folder for translations, but since file structure in this project doesn't exist... :)
Mamy możliwość stworzyć folder, np w `app/balancer/translations` i nawet wrzucić ten path gdzieś podczas INIT-u bota, aby już znał tą ścieżkę i nie trzeba było jej tak odgadywać jak niżej.

2024-03-01 11:00 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "EN.json"), encoding='utf-8') as english_file:
moglibyśmy tutaj zrobić funkcję "getTranslation("PL")" która zwróciłaby nam to z jsona w arrayce, czyli byłoby tak:

TRANSLATIONS["EN"] = self.getTranslations("EN");

Poza tym, mój zamysł był taki, aby aplikacja obsługiwałą tylko jeden plik json na raz. I to jest odpowiedzialnością programisty potem jak coś robi, żeby zmienić to np. gdzieś w konfigu albo w .env jaki jest domyślny język i na nim leci już cała apka dalej. 

Mogę nie mieć racji, więc jakie jest Twoje zdanie?

2024-03-01 11:00 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +        await msg.channel.send(TRANSLATIONS[LANG]["whois_stats"].format(player.name, player.dota_mmr, dotabuff, player_url, player.ladder_mmr, player.score, player.rank_score, len(player.matches), wi
możemy to jakoś na linie rozbić? Jest bardzo nieczytelnie

2024-03-01 11:00 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +            await msg.channel.send(TRANSLATIONS[LANG]["no_streak"].format(player.name))
czy możemy pozostawić tutaj `self.player_mention(player)` ?

2024-03-01 11:00 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +        #TODO HEREEEEEEEEEEE
chyba niepotrzebny komentarz

2024-03-01 13:25 UTC, PogSmok commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "PL.json"), encoding='utf-8') as polish_file:
Nie, używanie po prostu "EN.json" lub "PL.json" jako ścieżki nie działa zawsze i jest niezgodne z dobrymi praktykami.  W zależności od systemu operacyjnego oraz sposobu uruchamiania skryptu, python może inaczej zinterpretować ścieżkę i zwracać błędy.

2024-03-01 13:51 UTC, PogSmok commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "EN.json"), encoding='utf-8') as english_file:
Robienie funkcji to jest trochę lanie wody, już i tak zczytujemy ze słownika po zmiennej. Jeżeli o konfigurację chodzi, to zmienna LANG istnieje. Uważam, że nie ma sensu zmieniać/dodawać env lub konfiga, gdyż na ten moment tylko ten plik modyfikowany jest przez tłumaczenia i dodakowa abstrakcja tak prostej relacji tylko by zagmatwała sprawę.

2024-03-01 14:14 UTC, PogSmok commented on app/balancer/management/commands/discord_bot.py
> +#ideally this should be in a separate file/folder for translations, but since file structure in this project doesn't exist... :)
Dodałem w app/balancer/management/commands/command_translation

2024-03-01 16:18 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "EN.json"), encoding='utf-8') as english_file:
robienie po funkcji pozwoliłoby przenieść także skrypt do tłumaczeń poza discord_bot, zwłasza jeśli chcemy go użyć w dota_bot? Bo nie wiem czy chcemy, ale chyba tak. 

potem zamiast self.getTranslations, miałbyś self.translationService.getTranslations("EN")

może za daleko myślę w projekcie z takim długiem technologicznym

2024-03-01 16:22 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "PL.json"), encoding='utf-8') as polish_file:
Oczywiście, nie każę Ci brnąć w taką skrajność, ale zdaje się w projekcie mamy już złapany root dir projektu pod zmienną BASE_DIR

Mowię o pliku settings.py, gdzie jest BASE_DIR zdefiniowany i tam w paru miejscach jest os.path.join na tym:

na przykład: 

` 'LOCATION': os.path.join(BASE_DIR, 'cache'),`

2024-03-01 16:23 UTC, sellmark commented on app/balancer/management/commands/discord_bot.py
> +#ideally this should be in a separate file/folder for translations, but since file structure in this project doesn't exist... :)
możemy równie dobrze dać do root projektu, nic nam nie szkodzi i potem wykorzystać powyżej poruszony BASE_DIR

` 'LOCATION': os.path.join(BASE_DIR, 'translations'),`

po co później szukać tak głęboko tego jsona, zgodzisz się?

2024-03-03 19:51 UTC, PogSmok commented on app/balancer/management/commands/discord_bot.py
> +with open(os.path.join(os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__))), "EN.json"), encoding='utf-8') as english_file:
Jak będzie potrzeba to się doda, na razie nie widzę powodu. Do tego czasu może się struktura zmieni.

2024-03-18 11:49 UTC, closed without merging